[package]
name                      = "ipfs-api"
description               = "Implementation of an IPFS HTTP API client"
authors                   = ["Ferris Tseng <ferristseng@fastmail.fm>"]
edition                   = "2018"
documentation             = "https://docs.rs/ipfs-api"
repository                = "https://github.com/ferristseng/rust-ipfs-api"
keywords                  = ["ipfs"]
categories                = ["filesystem", "web-programming"]
version                   = "0.11.0"
readme                    = "../README.md"
license                   = "MIT OR Apache-2.0"

[badges]
travis-ci                 = { repository = "ferristseng/rust-ipfs-api" }

[features]
default                   = ["with-reqwest"]
with-hyper-tls            = ["with-hyper", "hyper-tls"]
with-hyper-rustls         = ["with-hyper", "hyper-rustls"]
with-hyper                = ["hyper", "hyper-multipart-rfc7578", "failure"]
with-reqwest              = ["reqwest", "failure", "futures-util"]
with-actix                = ["actix-http", "actix-multipart-rfc7578", "awc", "derive_more"]
with-builder              = ["typed-builder"]
# Old features, kept for compatibility
actix                     = ["with-actix"]
builder                   = ["with-builder"]

[dependencies]
actix-http                = { version = "2.2", optional = true }
actix-multipart-rfc7578   = { version = "0.4", optional = true }
awc                       = { version = "2.0", optional = true }
bytes                     = "1.0"
derive_more               = { version = "0.99", optional = true }
failure                   = { version = "0.1", optional = true }
futures                   = "0.3"
futures-util              = { version = "0.3", optional = true }
http                      = "0.2"
hyper                     = { version = "0.14", features = ["http1", "http2", "client"], optional = true }
hyper-tls                 = { version = "0.5", optional = true }
hyper-rustls              = { version = "0.22", optional = true }
hyper-multipart-rfc7578   = { version = "0.5", optional = true }
reqwest                   = { version = "0.11", features = ["multipart", "stream"], optional = true }
serde                     = { version = "1.0", features = ["derive"] }
serde_json                = "1.0"
serde_urlencoded          = "0.7"
tokio                     = "1.2"
tokio-util                = { version = "0.6", features = ["codec"] }
tracing                   = "0.1"
walkdir                   = "2.3"
dirs                      = "3.0"
parity-multiaddr          = "0.11"
typed-builder             = { version = "0.9", optional = true }

[dev-dependencies]
actix-http                = "2.2"
actix-rt                  = "1.0"
awc                       = "2.0"
hyper                     = "0.14"
hyper-tls                 = "0.5"
tar                       = "0.4"
tokio                     = { version = "1.2", features = ["rt-multi-thread", "macros", "time"] }
tokio-stream              = { version = "0.1", features = ["time"] }
tracing-subscriber        = { version = "0.2", features = ["fmt"] }
